# Generated by Django 4.1.7 on 2023-03-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=200)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.TextField()),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
